greeting:
  message: "hello"
quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: mypassword
    jdbc:
      url: jdbc:postgresql://localhost:5432/hibernate_orm_test
      driver: org.postgresql.Driver
  flyway:
    migrate-at-start: true
